# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rob/projects/Dungeon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rob/projects/Dungeon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rob/projects/Dungeon/CMakeFiles /home/rob/projects/Dungeon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rob/projects/Dungeon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dungeon

# Build rule for target.
dungeon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dungeon
.PHONY : dungeon

# fast build rule for target.
dungeon/fast:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/build
.PHONY : dungeon/fast

src/main/sources/Action.o: src/main/sources/Action.cpp.o

.PHONY : src/main/sources/Action.o

# target to build an object file
src/main/sources/Action.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Action.cpp.o
.PHONY : src/main/sources/Action.cpp.o

src/main/sources/Action.i: src/main/sources/Action.cpp.i

.PHONY : src/main/sources/Action.i

# target to preprocess a source file
src/main/sources/Action.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Action.cpp.i
.PHONY : src/main/sources/Action.cpp.i

src/main/sources/Action.s: src/main/sources/Action.cpp.s

.PHONY : src/main/sources/Action.s

# target to generate assembly for a file
src/main/sources/Action.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Action.cpp.s
.PHONY : src/main/sources/Action.cpp.s

src/main/sources/AllBlocks.o: src/main/sources/AllBlocks.cpp.o

.PHONY : src/main/sources/AllBlocks.o

# target to build an object file
src/main/sources/AllBlocks.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/AllBlocks.cpp.o
.PHONY : src/main/sources/AllBlocks.cpp.o

src/main/sources/AllBlocks.i: src/main/sources/AllBlocks.cpp.i

.PHONY : src/main/sources/AllBlocks.i

# target to preprocess a source file
src/main/sources/AllBlocks.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/AllBlocks.cpp.i
.PHONY : src/main/sources/AllBlocks.cpp.i

src/main/sources/AllBlocks.s: src/main/sources/AllBlocks.cpp.s

.PHONY : src/main/sources/AllBlocks.s

# target to generate assembly for a file
src/main/sources/AllBlocks.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/AllBlocks.cpp.s
.PHONY : src/main/sources/AllBlocks.cpp.s

src/main/sources/Circle.o: src/main/sources/Circle.cpp.o

.PHONY : src/main/sources/Circle.o

# target to build an object file
src/main/sources/Circle.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Circle.cpp.o
.PHONY : src/main/sources/Circle.cpp.o

src/main/sources/Circle.i: src/main/sources/Circle.cpp.i

.PHONY : src/main/sources/Circle.i

# target to preprocess a source file
src/main/sources/Circle.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Circle.cpp.i
.PHONY : src/main/sources/Circle.cpp.i

src/main/sources/Circle.s: src/main/sources/Circle.cpp.s

.PHONY : src/main/sources/Circle.s

# target to generate assembly for a file
src/main/sources/Circle.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Circle.cpp.s
.PHONY : src/main/sources/Circle.cpp.s

src/main/sources/ConnAccepter.o: src/main/sources/ConnAccepter.cpp.o

.PHONY : src/main/sources/ConnAccepter.o

# target to build an object file
src/main/sources/ConnAccepter.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/ConnAccepter.cpp.o
.PHONY : src/main/sources/ConnAccepter.cpp.o

src/main/sources/ConnAccepter.i: src/main/sources/ConnAccepter.cpp.i

.PHONY : src/main/sources/ConnAccepter.i

# target to preprocess a source file
src/main/sources/ConnAccepter.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/ConnAccepter.cpp.i
.PHONY : src/main/sources/ConnAccepter.cpp.i

src/main/sources/ConnAccepter.s: src/main/sources/ConnAccepter.cpp.s

.PHONY : src/main/sources/ConnAccepter.s

# target to generate assembly for a file
src/main/sources/ConnAccepter.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/ConnAccepter.cpp.s
.PHONY : src/main/sources/ConnAccepter.cpp.s

src/main/sources/ConnManager.o: src/main/sources/ConnManager.cpp.o

.PHONY : src/main/sources/ConnManager.o

# target to build an object file
src/main/sources/ConnManager.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/ConnManager.cpp.o
.PHONY : src/main/sources/ConnManager.cpp.o

src/main/sources/ConnManager.i: src/main/sources/ConnManager.cpp.i

.PHONY : src/main/sources/ConnManager.i

# target to preprocess a source file
src/main/sources/ConnManager.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/ConnManager.cpp.i
.PHONY : src/main/sources/ConnManager.cpp.i

src/main/sources/ConnManager.s: src/main/sources/ConnManager.cpp.s

.PHONY : src/main/sources/ConnManager.s

# target to generate assembly for a file
src/main/sources/ConnManager.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/ConnManager.cpp.s
.PHONY : src/main/sources/ConnManager.cpp.s

src/main/sources/Connection.o: src/main/sources/Connection.cpp.o

.PHONY : src/main/sources/Connection.o

# target to build an object file
src/main/sources/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Connection.cpp.o
.PHONY : src/main/sources/Connection.cpp.o

src/main/sources/Connection.i: src/main/sources/Connection.cpp.i

.PHONY : src/main/sources/Connection.i

# target to preprocess a source file
src/main/sources/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Connection.cpp.i
.PHONY : src/main/sources/Connection.cpp.i

src/main/sources/Connection.s: src/main/sources/Connection.cpp.s

.PHONY : src/main/sources/Connection.s

# target to generate assembly for a file
src/main/sources/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Connection.cpp.s
.PHONY : src/main/sources/Connection.cpp.s

src/main/sources/Entity.o: src/main/sources/Entity.cpp.o

.PHONY : src/main/sources/Entity.o

# target to build an object file
src/main/sources/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Entity.cpp.o
.PHONY : src/main/sources/Entity.cpp.o

src/main/sources/Entity.i: src/main/sources/Entity.cpp.i

.PHONY : src/main/sources/Entity.i

# target to preprocess a source file
src/main/sources/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Entity.cpp.i
.PHONY : src/main/sources/Entity.cpp.i

src/main/sources/Entity.s: src/main/sources/Entity.cpp.s

.PHONY : src/main/sources/Entity.s

# target to generate assembly for a file
src/main/sources/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Entity.cpp.s
.PHONY : src/main/sources/Entity.cpp.s

src/main/sources/Game.o: src/main/sources/Game.cpp.o

.PHONY : src/main/sources/Game.o

# target to build an object file
src/main/sources/Game.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Game.cpp.o
.PHONY : src/main/sources/Game.cpp.o

src/main/sources/Game.i: src/main/sources/Game.cpp.i

.PHONY : src/main/sources/Game.i

# target to preprocess a source file
src/main/sources/Game.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Game.cpp.i
.PHONY : src/main/sources/Game.cpp.i

src/main/sources/Game.s: src/main/sources/Game.cpp.s

.PHONY : src/main/sources/Game.s

# target to generate assembly for a file
src/main/sources/Game.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Game.cpp.s
.PHONY : src/main/sources/Game.cpp.s

src/main/sources/Interpreter.o: src/main/sources/Interpreter.cpp.o

.PHONY : src/main/sources/Interpreter.o

# target to build an object file
src/main/sources/Interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Interpreter.cpp.o
.PHONY : src/main/sources/Interpreter.cpp.o

src/main/sources/Interpreter.i: src/main/sources/Interpreter.cpp.i

.PHONY : src/main/sources/Interpreter.i

# target to preprocess a source file
src/main/sources/Interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Interpreter.cpp.i
.PHONY : src/main/sources/Interpreter.cpp.i

src/main/sources/Interpreter.s: src/main/sources/Interpreter.cpp.s

.PHONY : src/main/sources/Interpreter.s

# target to generate assembly for a file
src/main/sources/Interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Interpreter.cpp.s
.PHONY : src/main/sources/Interpreter.cpp.s

src/main/sources/Map.o: src/main/sources/Map.cpp.o

.PHONY : src/main/sources/Map.o

# target to build an object file
src/main/sources/Map.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Map.cpp.o
.PHONY : src/main/sources/Map.cpp.o

src/main/sources/Map.i: src/main/sources/Map.cpp.i

.PHONY : src/main/sources/Map.i

# target to preprocess a source file
src/main/sources/Map.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Map.cpp.i
.PHONY : src/main/sources/Map.cpp.i

src/main/sources/Map.s: src/main/sources/Map.cpp.s

.PHONY : src/main/sources/Map.s

# target to generate assembly for a file
src/main/sources/Map.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Map.cpp.s
.PHONY : src/main/sources/Map.cpp.s

src/main/sources/Player.o: src/main/sources/Player.cpp.o

.PHONY : src/main/sources/Player.o

# target to build an object file
src/main/sources/Player.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Player.cpp.o
.PHONY : src/main/sources/Player.cpp.o

src/main/sources/Player.i: src/main/sources/Player.cpp.i

.PHONY : src/main/sources/Player.i

# target to preprocess a source file
src/main/sources/Player.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Player.cpp.i
.PHONY : src/main/sources/Player.cpp.i

src/main/sources/Player.s: src/main/sources/Player.cpp.s

.PHONY : src/main/sources/Player.s

# target to generate assembly for a file
src/main/sources/Player.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Player.cpp.s
.PHONY : src/main/sources/Player.cpp.s

src/main/sources/Room.o: src/main/sources/Room.cpp.o

.PHONY : src/main/sources/Room.o

# target to build an object file
src/main/sources/Room.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Room.cpp.o
.PHONY : src/main/sources/Room.cpp.o

src/main/sources/Room.i: src/main/sources/Room.cpp.i

.PHONY : src/main/sources/Room.i

# target to preprocess a source file
src/main/sources/Room.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Room.cpp.i
.PHONY : src/main/sources/Room.cpp.i

src/main/sources/Room.s: src/main/sources/Room.cpp.s

.PHONY : src/main/sources/Room.s

# target to generate assembly for a file
src/main/sources/Room.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Room.cpp.s
.PHONY : src/main/sources/Room.cpp.s

src/main/sources/RoomManager.o: src/main/sources/RoomManager.cpp.o

.PHONY : src/main/sources/RoomManager.o

# target to build an object file
src/main/sources/RoomManager.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/RoomManager.cpp.o
.PHONY : src/main/sources/RoomManager.cpp.o

src/main/sources/RoomManager.i: src/main/sources/RoomManager.cpp.i

.PHONY : src/main/sources/RoomManager.i

# target to preprocess a source file
src/main/sources/RoomManager.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/RoomManager.cpp.i
.PHONY : src/main/sources/RoomManager.cpp.i

src/main/sources/RoomManager.s: src/main/sources/RoomManager.cpp.s

.PHONY : src/main/sources/RoomManager.s

# target to generate assembly for a file
src/main/sources/RoomManager.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/RoomManager.cpp.s
.PHONY : src/main/sources/RoomManager.cpp.s

src/main/sources/Settings.o: src/main/sources/Settings.cpp.o

.PHONY : src/main/sources/Settings.o

# target to build an object file
src/main/sources/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Settings.cpp.o
.PHONY : src/main/sources/Settings.cpp.o

src/main/sources/Settings.i: src/main/sources/Settings.cpp.i

.PHONY : src/main/sources/Settings.i

# target to preprocess a source file
src/main/sources/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Settings.cpp.i
.PHONY : src/main/sources/Settings.cpp.i

src/main/sources/Settings.s: src/main/sources/Settings.cpp.s

.PHONY : src/main/sources/Settings.s

# target to generate assembly for a file
src/main/sources/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/Settings.cpp.s
.PHONY : src/main/sources/Settings.cpp.s

src/main/sources/TripleMutex.o: src/main/sources/TripleMutex.cpp.o

.PHONY : src/main/sources/TripleMutex.o

# target to build an object file
src/main/sources/TripleMutex.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/TripleMutex.cpp.o
.PHONY : src/main/sources/TripleMutex.cpp.o

src/main/sources/TripleMutex.i: src/main/sources/TripleMutex.cpp.i

.PHONY : src/main/sources/TripleMutex.i

# target to preprocess a source file
src/main/sources/TripleMutex.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/TripleMutex.cpp.i
.PHONY : src/main/sources/TripleMutex.cpp.i

src/main/sources/TripleMutex.s: src/main/sources/TripleMutex.cpp.s

.PHONY : src/main/sources/TripleMutex.s

# target to generate assembly for a file
src/main/sources/TripleMutex.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/TripleMutex.cpp.s
.PHONY : src/main/sources/TripleMutex.cpp.s

src/main/sources/main.o: src/main/sources/main.cpp.o

.PHONY : src/main/sources/main.o

# target to build an object file
src/main/sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/main.cpp.o
.PHONY : src/main/sources/main.cpp.o

src/main/sources/main.i: src/main/sources/main.cpp.i

.PHONY : src/main/sources/main.i

# target to preprocess a source file
src/main/sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/main.cpp.i
.PHONY : src/main/sources/main.cpp.i

src/main/sources/main.s: src/main/sources/main.cpp.s

.PHONY : src/main/sources/main.s

# target to generate assembly for a file
src/main/sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/main.cpp.s
.PHONY : src/main/sources/main.cpp.s

src/main/sources/publicInfo.o: src/main/sources/publicInfo.cpp.o

.PHONY : src/main/sources/publicInfo.o

# target to build an object file
src/main/sources/publicInfo.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/publicInfo.cpp.o
.PHONY : src/main/sources/publicInfo.cpp.o

src/main/sources/publicInfo.i: src/main/sources/publicInfo.cpp.i

.PHONY : src/main/sources/publicInfo.i

# target to preprocess a source file
src/main/sources/publicInfo.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/publicInfo.cpp.i
.PHONY : src/main/sources/publicInfo.cpp.i

src/main/sources/publicInfo.s: src/main/sources/publicInfo.cpp.s

.PHONY : src/main/sources/publicInfo.s

# target to generate assembly for a file
src/main/sources/publicInfo.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/publicInfo.cpp.s
.PHONY : src/main/sources/publicInfo.cpp.s

src/main/sources/util/Dbg.o: src/main/sources/util/Dbg.cpp.o

.PHONY : src/main/sources/util/Dbg.o

# target to build an object file
src/main/sources/util/Dbg.cpp.o:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/util/Dbg.cpp.o
.PHONY : src/main/sources/util/Dbg.cpp.o

src/main/sources/util/Dbg.i: src/main/sources/util/Dbg.cpp.i

.PHONY : src/main/sources/util/Dbg.i

# target to preprocess a source file
src/main/sources/util/Dbg.cpp.i:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/util/Dbg.cpp.i
.PHONY : src/main/sources/util/Dbg.cpp.i

src/main/sources/util/Dbg.s: src/main/sources/util/Dbg.cpp.s

.PHONY : src/main/sources/util/Dbg.s

# target to generate assembly for a file
src/main/sources/util/Dbg.cpp.s:
	$(MAKE) -f CMakeFiles/dungeon.dir/build.make CMakeFiles/dungeon.dir/src/main/sources/util/Dbg.cpp.s
.PHONY : src/main/sources/util/Dbg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dungeon"
	@echo "... src/main/sources/Action.o"
	@echo "... src/main/sources/Action.i"
	@echo "... src/main/sources/Action.s"
	@echo "... src/main/sources/AllBlocks.o"
	@echo "... src/main/sources/AllBlocks.i"
	@echo "... src/main/sources/AllBlocks.s"
	@echo "... src/main/sources/Circle.o"
	@echo "... src/main/sources/Circle.i"
	@echo "... src/main/sources/Circle.s"
	@echo "... src/main/sources/ConnAccepter.o"
	@echo "... src/main/sources/ConnAccepter.i"
	@echo "... src/main/sources/ConnAccepter.s"
	@echo "... src/main/sources/ConnManager.o"
	@echo "... src/main/sources/ConnManager.i"
	@echo "... src/main/sources/ConnManager.s"
	@echo "... src/main/sources/Connection.o"
	@echo "... src/main/sources/Connection.i"
	@echo "... src/main/sources/Connection.s"
	@echo "... src/main/sources/Entity.o"
	@echo "... src/main/sources/Entity.i"
	@echo "... src/main/sources/Entity.s"
	@echo "... src/main/sources/Game.o"
	@echo "... src/main/sources/Game.i"
	@echo "... src/main/sources/Game.s"
	@echo "... src/main/sources/Interpreter.o"
	@echo "... src/main/sources/Interpreter.i"
	@echo "... src/main/sources/Interpreter.s"
	@echo "... src/main/sources/Map.o"
	@echo "... src/main/sources/Map.i"
	@echo "... src/main/sources/Map.s"
	@echo "... src/main/sources/Player.o"
	@echo "... src/main/sources/Player.i"
	@echo "... src/main/sources/Player.s"
	@echo "... src/main/sources/Room.o"
	@echo "... src/main/sources/Room.i"
	@echo "... src/main/sources/Room.s"
	@echo "... src/main/sources/RoomManager.o"
	@echo "... src/main/sources/RoomManager.i"
	@echo "... src/main/sources/RoomManager.s"
	@echo "... src/main/sources/Settings.o"
	@echo "... src/main/sources/Settings.i"
	@echo "... src/main/sources/Settings.s"
	@echo "... src/main/sources/TripleMutex.o"
	@echo "... src/main/sources/TripleMutex.i"
	@echo "... src/main/sources/TripleMutex.s"
	@echo "... src/main/sources/main.o"
	@echo "... src/main/sources/main.i"
	@echo "... src/main/sources/main.s"
	@echo "... src/main/sources/publicInfo.o"
	@echo "... src/main/sources/publicInfo.i"
	@echo "... src/main/sources/publicInfo.s"
	@echo "... src/main/sources/util/Dbg.o"
	@echo "... src/main/sources/util/Dbg.i"
	@echo "... src/main/sources/util/Dbg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

